# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-11 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20170705_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
